# Generated by Django 6.0.1 on 2026-07-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_difficult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='lapse_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='quiz_correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='quiz_wrong_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='review_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='review_ease',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='word',
            name='review_interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
